

#source = "resources/standalone/HelloWorld.stella"
#main = "HelloWorld/HelloWorld"
source = "resources/standalone/MacroTest.stella"
main = "MacroTest/MacroTest"

build = "resources/build.jar"

[core]
Core = "resources/library/Core.stella"
Math = "resources/library/Math.stella"
